namespace DefaultNamespace
{
    public enum Note
    {
        C,
        CSharp,
        D,
        DSharp,
        E,
        F,
        FSharp,
        G,
        GSharp,
        A,
        ASharp,
        B
    }

    public class Constants
    {
        public static string[] ChordNames =
        {
            "Major",
            "Minor",
            "7",
            "5",
            "dim",
            "dim7",
            "aug",
            "sus2",
            "sus4",
            "maj7",
            "m7",
            "7sus4",
            "maj9",
            "maj11",
            "maj13",
            "maj9#11",
            "maj13#11",
            "add9",
            "6add9",
            "maj7b5",
            "maj7#5",
            "m6",
            "m9",
            "m11",
            "m13",
            "madd9",
            "m6add9",
            "mmaj7",
            "mmaj9",
            "m7b5",
            "m7#5",
            "6",
            "9",
            "11",
            "13",
            "7b5",
            "7#5",
            "7b9",
            "7#9",
            "7(b5,b9)",
            "7(b5,#9)",
            "7(#5,b9)",
            "7(#5,#9)",
            "9b5",
            "9#5",
            "13#11",
            "13b9",
            "11b9",
            "sus2sus4",
            "-5"
        };
    }
}